<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- xunit uses underscore-based naming convention -->
    <NoWarn>$(NoWarn);CA1707</NoWarn>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CloudImaging.ImagingCoreApi\CloudImaging.ImagingCoreApi.csproj" />
    <ProjectReference Include="..\..\src\CloudImaging.Contracts\CloudImaging.Contracts.csproj" />
  </ItemGroup>

</Project>
