<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- xunit uses underscore-based naming convention -->
    <NoWarn>$(NoWarn);CA1707</NoWarn>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CloudImaging.MediaBuilder\CloudImaging.MediaBuilder.csproj" />
  </ItemGroup>

</Project>
